# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the workflow will run
on:
  # Triggers the workflow on push events but only for the master branch
  push:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: [self-hosted, doc-build]

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      #- uses: actions/checkout@v2

      # Runs a set of commands using the runners shell
      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DNTDoc ] && rm -rf DNTDoc
          [ -d dotnet-twain-docs ] && rm -rf dotnet-twain-docs
          [ -d Docs-Template-Repo-Old-Master ] && rm -rf Docs-Template-Repo-Old-Master
          [ ! -d DNTDoc ] && mkdir -p DNTDoc
          git clone --depth 1 https://github.com/dynamsoft-docs/dotnet-twain-docs.git dotnet-twain-docs
          git clone --depth 1 --branch old-master https://github.com/dynamsoft-docs/Docs-Template-Repo.git Docs-Template-Repo-Old-Master
          cp -rfp ./dotnet-twain-docs/* ./DNTDoc/
          cp -rfp ./Docs-Template-Repo-Old-Master/* ./DNTDoc/
          cd DNTDoc && bundle install && bundle exec jekyll build

          python3 /home/ubuntu/ftp.py /home/ubuntu/DNTDoc/_site/ ./www.dynamsoft.com/dotnet-twain/docs/ prod

      - name: Trigger Webhook 
        run: | 
          curl -X POST -H "${{ secrets.WEBHOOK_USER }}" -H "${{ secrets.WEBHOOK_TOKEN }}" -H "Content-Type: application/json" -d "[\"/dotnet-twain/docs/*\"]" ${{ secrets.WEBHOOK_URL }}

      - name: Run a multi-line script
        run: |
          cd /home/ubuntu
          [ -d DNTDoc ] && rm -rf DNTDoc
          [ -d dotnet-twain-docs ] && rm -rf dotnet-twain-docs
          [ -d Docs-Template-Repo-Old-Master ] && rm -rf Docs-Template-Repo-Old-Master

          
